/*
  Automatically generated by Autodist 1.4.  Do not edit.

  Generated: Fri Aug  7 10:08:57 EEST 2009 by priikone
  Distribution: Toolkit
  License: distdir/TOOLKIT
*/

#ifndef _SILC_DISTDEFS_H
#define _SILC_DISTDEFS_H

#define SILC_DIST_APPS 1
#define SILC_DIST_ASN1 1
#define SILC_DIST_CLIENTLIB 1
#define SILC_DIST_COMPILER 1
#define SILC_DIST_CRYPTO 1
#define SILC_DIST_DOC 1
#define SILC_DIST_HTTP 1
#define SILC_DIST_IDCACHE 1
#define SILC_DIST_INCLUDES 1
#define SILC_DIST_LIB 1
#define SILC_DIST_MATH 1
#define SILC_DIST_SFTP 1
#define SILC_DIST_SILC 1
#define SILC_DIST_SIM 1
#define SILC_DIST_SKR 1
#define SILC_DIST_TMA 1
#define SILC_DIST_TOOLKIT 1
#define SILC_DIST_VCARD 1

#endif /* _SILC_DISTDEFS_H */
